### PR TITLE
modified clock.cc to display both the 12H and 24H clock systems

### PR DESCRIPTION
**Pull request by realhefd**
modified clock.cc to display both the 12H and 24H clock systems

### CODE REVIEW

**Comment by Muriukidavid** [comment]
Please keep only one copy of the files. You have atm folder and still atm files outside that folder. Keep it clean. are they different?

**Comment by realhefd** [comment]
Yes they are, so should I delete that folder and only leave atm files that are outside it ?

**Comment by Muriukidavid** [comment]
I was going to ask you the same question. What are you to do?

**Comment by realhefd** [comment]
I deleted the atm folder and made a commit, a push and a pull request

**Comment by realhefd** [comment]
Was that okay ?

**Pull request closed without merging**
