### PR TITLE
ATM simulation implementation using C++ (atm.cc and atm.h files) [in the parent dir]

### PR DESCRIPTION
**Pull request by realhefd**
I deleted the atm folder because the atm files it had were the same as the ones outside it, so it's cleaned

### CODE REVIEW

**Comment by Muriukidavid** [comment]
The clock is still not done properly done, you need to make two different classes for 12hr and 24hr clock derived/based-on the time class.

**Comment by realhefd** [comment]
Let me make the changes and commit again

**Comment by Muriukidavid** [comment]
the time setting function is ok for both of them, what you need is a different time display function for each.

**Comment by realhefd** [comment]
but I think that's just what I did,   coz I have the "displayTime(void)"
function to display in 12H format and "displayTime_12Hours(void)" function
for the 24H format.  Could I be wrong

**Pull request closed without merging**
